import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Main book navigation sidebar
  bookSidebar: [
    'intro',
    'weekly-schedule',
    'assessments',
    {
      type: 'category',
      label: 'Module 1: The Robotic Nervous System (ROS 2)',
      link: {
        type: 'generated-index',
        description: 'Learn about ROS 2, the middleware that acts as the nervous system for modern robots. This module covers nodes, topics, services, URDF modeling, and launch files.',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'module1-robotic-nervous-system',
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 2: The Digital Twin (Gazebo & Unity)',
      link: {
        type: 'generated-index',
        description: 'Explore physics simulation and high-fidelity rendering for robots. Learn to build simulated worlds in Gazebo, simulate sensors, and create photorealistic scenes in Unity.',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'module2-the-digital-twin',
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 3: The AI-Robot Brain (NVIDIA Isaac)',
      link: {
        type: 'generated-index',
        description: 'Discover how NVIDIA Isaac Sim and Isaac ROS accelerate perception, navigation, and control for humanoid robotics. Learn GPU-accelerated VSLAM, synthetic data generation, and path planning for bipedal locomotion.',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'module3-ai-robot-brain',
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action (VLA)',
      link: {
        type: 'generated-index',
        description: 'Explore the convergence of language models and robotics. Learn how humanoid robots combine vision, language understanding, and action planning to execute complex tasks from natural language commands.',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'module4-vision-language-action',
        },
      ],
    },
  ],
};

export default sidebars;
