import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Main book navigation sidebar
  bookSidebar: [
    'intro',
    {
      type: 'category',
      label: '1. Introduction',
      link: {
        type: 'doc',
        id: 'introduction/index',
      },
      items: [
        'introduction/what-is-physical-ai',
        'introduction/humanoid-robotics-overview',
      ],
    },
    {
      type: 'autogenerated',
      dirName: 'module1-robotic-nervous-system',
    },
    {
      type: 'autogenerated',
      dirName: 'module2-the-digital-twin',
    },
    {
      type: 'autogenerated',
      dirName: 'module3-ai-robot-brain',
    },
    {
      type: 'category',
      label: '2. Core Modules',
      link: {
        type: 'doc',
        id: 'modules/index',
      },
      items: [
        'modules/perception',
        'modules/locomotion',
        'modules/manipulation',
      ],
    },
    {
      type: 'category',
      label: '3. Applications',
      link: {
        type: 'doc',
        id: 'applications/index',
      },
      items: [
        'applications/industrial',
        'applications/healthcare',
        'applications/service-robotics',
      ],
    },
  ],

  // Tutorial sidebar (keep for reference/examples)
  tutorialSidebar: [{type: 'autogenerated', dirName: 'tutorial-basics'}],
};

export default sidebars;
