from pydantic import BaseModel, Field
from typing import List, Optional
from datetime import datetime


class Question(BaseModel):
    """
    A user query submitted to the system about book content
    """
    id: str = Field(..., description="Unique identifier for the question")
    content: str = Field(..., min_length=1, max_length=1000, description="The text of the user's question")
    book_id: Optional[str] = Field(None, description="Identifier for the specific book (if multiple books supported)")
    timestamp: datetime = Field(default_factory=datetime.now, description="When the question was submitted")
    selected_text: Optional[str] = Field(None, min_length=1, max_length=500, description="Relevant text selected by user when asking the question")


class BookContentChunk(BaseModel):
    """
    Segments of book content stored in the vector database for retrieval
    """
    id: str = Field(..., description="Unique identifier for the chunk")
    content: str = Field(..., min_length=10, max_length=2000, description="The text content of the chunk")
    book_id: str = Field(..., description="Identifier for the book this chunk belongs to")
    chapter: Optional[str] = Field(None, description="Chapter or section information")
    page_number: Optional[int] = Field(None, description="Page number in the original book")
    document_position: int = Field(..., ge=0, description="Position of this chunk in the document")
    # Using Any type for embedding since pydantic has issues with list[float] in some versions
    embedding: List[float] = Field(..., description="Vector embedding representation of the content")
    metadata: Optional[dict] = Field(None, description="Additional metadata about the content chunk")


class Answer(BaseModel):
    """
    Response generated by the agent based on retrieved book content
    """
    id: str = Field(..., description="Unique identifier for the answer")
    question_id: str = Field(..., description="Reference to the question being answered")
    content: str = Field(..., min_length=1, description="The text answer to the question")
    timestamp: datetime = Field(default_factory=datetime.now, description="When the answer was generated")
    confidence_score: Optional[float] = Field(None, ge=0.0, le=1.0, description="Confidence score of the answer (0.0-1.0)")


class SourceReference(BaseModel):
    """
    Specific citation to the book content chunk(s) used to generate an answer
    """
    id: str = Field(..., description="Unique identifier for the source reference")
    answer_id: str = Field(..., description="Reference to the answer this source relates to")
    chunk_id: str = Field(..., description="Reference to the book content chunk used")
    relevance_score: float = Field(..., ge=0.0, le=1.0, description="Relevance score of this chunk to the question (0.0-1.0)")
    content_snippet: str = Field(..., description="Excerpt from the referenced content")
    source_location: str = Field(..., min_length=1, description="Location information (e.g., book title, chapter, page)")
    confidence_score: Optional[float] = Field(None, ge=0.0, le=1.0, description="Confidence in the accuracy of this source reference")
    page_reference: Optional[str] = Field(None, description="Specific page reference for the citation")
    section_title: Optional[str] = Field(None, description="Title of the section where the content appears")
    metadata: Optional[dict] = Field(None, description="Additional metadata about the source reference")